secrets:
  mongo-root-username:
    file: ./secrets/mongo-root-username
  mongo-root-password:
    file: secrets/mongo-root-password
  mongo-connection-string:
    file: secrets/mongo-connection-string

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    secrets:
      - mongo-root-username
      - mongo-root-password
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password

  wagw:
    build: ./wagw
    restart: unless-stopped
    volumes:
      - ./volumes/wagw/wwebjs_auth:/app/.wwebjs_auth
      - ./volumes/wagw/wwebjs_cache:/app/.wwebjs_cache

  svalbard:
    build: ./svalbard
    restart: unless-stopped
    secrets:
      - mongo-connection-string
    volumes:
      - ./volumes/svalbard:/data
    environment:
      - MONGO_CONNECTION_STRING_FILE: /run/secrets/mongo-connection-string
