secrets:
  mongo-root-username:
    file: ./secrets/mongo-root-username
  mongo-root-password:
    file: secrets/mongo-root-password

services:
  mongo:
    image: mongo
    restart: unless-stopped
    secrets:
      - mongo-root-username
      - mongo-root-password
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password

